base_url: /fosslight-guide
title: FOSSLight
lang: ko
description: FOSSLight Korean Guide

remote_theme: fosslight/jekyll-rtd-theme

top_link: "https://fosslight.github.io/fosslight-guide-en"
top_link_word: "EN"

google:
  gtag: UA-196813776-3
  
readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
